### ISSUE TITLE
[Feature] Script to add SSL policy to all or multiple S3 buckets

### ISSUE THREAD

**Issue by ghost** [skildops/aws-utilities#1]
### Prerequisites

- [X] I have checked to make sure that this issue has not already been filed

### Describe the solution you'd like

A script that will read existing policy of S3 bucket and if SSL policy does not exist then append it to the existing policy to attach one to the bucket

**Comment by paliwalvimal** [comment]
script added: https://raw.githubusercontent.com/skildops/aws-utilities/main/s3_ssl_bucket_policy.py
